# 
# Home Assistant Automation Blueprint
#
# Sends notifications to open the curtain based on the temperature, 
# if the temperature reading of a given sensor is above a certain degree. 
#
# Gaet81, March 2022
#

blueprint:
  name: 'Notification to open curtains'
  description: Notification to open curtains if it is cold
  domain: automation
  input: 
    temperature_sensor: 
      name: Temperature Sensor
      description: 'The sensor used for reading the temperature.'
      selector: 
        entity:
          domain: sensor
          device_class: temperature
    temperature:
      name: 'Temperature'
      description: 'The outside temperature above which the notification should be sent.'
      default: 16
      selector: 
        number:
          min: 0
          step: 1
          max: 25
          mode: slider
    device_identifier:
      name: Device to notify
      description: >
        The device to receive the notification; it needs to run the official 
        Home Assistant app to receive notifications.
      selector: 
        device:
          integration: mobile_app

# We will have two triggers, for the two different reminders. 
# However, a reminder will be ignored if the door or window is already closed by then. 
- platform: numeric_state
  entity_id: !input temperature_sensor
  below: !input temperature
# Send a notification to the mobile device. 
action:
- device_id: !input device_identifier
  domain: mobile_app
  type: notify
  message: 'Time to open curtain.'
  title: 'Open curtain!'
mode: single
